sudo: false
language: smalltalk
os:
- linux
- osx
smalltalk:
- Squeak64-5.2
- Squeak64-trunk
jobs:
  include:
  - stage: deploy
    language: node_js
    os: linux
    node_js:
    - "8"
    env:
      PKG_CACHE_PATH: node-cache
      JFROG_CLI_OFFER_CONFIG: false
    cache:
      yarn: true
      directories:
      - node-cache
    install:
    - yarn install
    script:
    - yarn build
    after_script:
    - yarn global add jfrog-cli-go
    - jfrog bt version-create --user cmfcmf --key $BINTRAY_KEY                                  cmfcmf/MagicMouse/node-bridge/latest || true
    - jfrog bt upload         --user cmfcmf --key $BINTRAY_KEY --publish --override "./build/*" cmfcmf/MagicMouse/node-bridge/latest
